#
# Copyright 2026 migueltt and/or Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ======================================================================================================================
[versions]
android-gradle-plugin = "9.0.1"
kotlin = "2.3.10"
spotless = "8.2.1"

# Core Libraries
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.10.0"
kotlinx-collections-immutable = "0.4.0"

androidSdkCompile = "36"
androidSdkMin = "24"
androidSdkTarget = "36"

androidx-activity = "1.12.4"
androidx-espresso = "3.7.0"
androidx-testExt = "1.3.0"

# KMP Compose
compose-multiplatform = "1.10.1"
compose-hot-reload = "1.0.0"
compose-material3 = "1.9.0"
compose-material-icons-extended = "1.7.3"
compose-lifecycle = "2.9.6"

# Old nav
# compose-navigation = "2.9.1"
# KMP navigation3
# WARNING: `1.1.0-alpha02` --> requires compose-multiplatform = "1.10.1"
compose-multiplatform-navigation = "1.1.0-alpha03"
# WARNING: `1.3.0-alpha04` --> requires compose-multiplatform = "1.10.1"
compose-multiplatform-adaptive = "1.3.0-alpha05"
compose-multiplatform-lifecycle = "2.10.0-alpha08"

ktor = "3.4.0"
logback = "1.5.32"

junit = "4.13.2"

# ======================================================================================================================
[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradle-plugin" }

kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

ktor = { id = "io.ktor.plugin", version.ref = "ktor" }

spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

# ======================================================================================================================
[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization"}

androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-material-icons-extended" }
compose-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-lifecycle" }
compose-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "compose-lifecycle" }

# Old nav
# androidx-compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-navigation" }

# KMP navigation3
multiplatform-navigation-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "compose-multiplatform-navigation" }
multiplatform-navigation-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation3", version.ref = "compose-multiplatform-adaptive" }
multiplatform-navigation-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "compose-multiplatform-lifecycle" }

# KMP Desktop
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

# Ktor
ktor-utils = { module = "io.ktor:ktor-utils", version.ref = "ktor"}
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

## Ktor Client
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
## Ktor Server
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Unit Tests
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

# TODO: review test libraries
junit = { module = "junit:junit", version.ref = "junit" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }

# ======================================================================================================================
[bundles]

kotlinx-core = [
    "kotlinx-coroutines-core",
    "kotlinx-datetime",
    "kotlinx-serialization-core",
    "kotlinx-collections-immutable",
]

compose-multiplatform = [
    "compose-foundation",
    "compose-runtime",
    "compose-ui",
    "compose-ui-tooling-preview",
    "compose-material3",
    "compose-material-icons-extended",
    "compose-components-resources",
]

compose-lifecycle = [
    "compose-lifecycle-viewmodel",
    "compose-lifecycle-runtime",
]

compose-navigation = [
    "kotlinx-serialization-core",
    "multiplatform-navigation-ui",
    "multiplatform-navigation-adaptive",
    "multiplatform-navigation-lifecycle-viewmodel",
]

ktor-client = [
    "ktor-client-core",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json",
]

ktor-server = [
    "ktor-server-core",
    "ktor-server-content-negotiation",
    "ktor-serialization-kotlinx-json",
    "ktor-server-netty",
    "logback",
]

ktor-server-test = [
    "ktor-server-test-host",
    "kotlin-test-junit",
]

android-test = [
    "junit",
    "androidx-testExt-junit",
    "androidx-espresso-core",
]